packages:
  - "templates/*"

catalog:
  # Prod dependencies
  "@nuxt/content": "^3.0.1"
  "@nuxt/icon": "^1.10.3"
  "@nuxt/image": "^1.9.0"
  "@nuxt/ui": "^3.0.0-alpha.12"
  "@nuxt/ui-pro": "^3.0.0-alpha.12"
  "@nuxthq/studio": "^2.2.1"
  "@nuxthub/core": "^0.8.15"
  "@nuxtjs/color-mode": "^3.5.2"
  "@nuxtjs/supabase": "^1.4.6"
  "@pinia/colada-nuxt": "^0.0.4"
  "@pinia/nuxt": "^0.9.0"
  "@supabase/supabase-js": "^2.49.1"
  "@unocss/reset": "^65.4.3"
  "@vite-pwa/nuxt": "^0.10.6"
  "@vueuse/nuxt": "^12.5.0"
  "class-variance-authority": "^0.7.1"
  "clsx": "^2.1.1"
  "drizzle-orm": "^0.39.0"
  "h3-zod": "^0.5.3"
  "lucide-vue-next": "^0.475.0"
  "nuxt": "^3.15.4"
  "nuxt-auth-utils": "^0.5.15"
  "radix-vue": "^1.9.13"
  "shadcn-nuxt": "^0.11.3"
  "tailwind-merge": "^3.0.1"
  # Dev dependencies
  "@iconify-json/heroicons": "^1.2.2"
  "@iconify-json/simple-icons": "^1.2.22"
  "@iconify-json/lucide": "^1.2.25"
  "@nuxt/eslint": "^0.7.5"
  "@unocss/nuxt": "^65.4.3"
  "better-sqlite3": "^11.8.1"
  "drizzle-kit": "^0.30.2"
  "unocss": "^65.4.3"
  "unocss-preset-animations": "^1.1.1"
  "unocss-preset-shadcn": "^0.3.0"
  "shadcn-vue": "^0.11.3"
  "vue-tsc": "~2.1.10"
  "wrangler": "^3.105.1"
