packages:
  - 'templates/*'

catalog:
  "@nuxt/ui": "^3.0.0-alpha.12"
  "@nuxt/ui-pro": "^3.0.0-alpha.12"
  "@nuxt/content": "^3.0.1"
  "@nuxt/image": "^1.9.0"
  "@nuxthq/studio": "^2.2.1"
  "@nuxthub/core": "^0.8.15"
  "@pinia/colada-nuxt": "^0.0.4"
  "@pinia/nuxt": "^0.9.0"
  "@vite-pwa/nuxt": "0.10.6"
  "@vueuse/nuxt": "^12.5.0"
  "drizzle-orm": "^0.39.0"
  "h3-zod": "^0.5.3"
  "nuxt": "^3.15.4"
  "nuxt-auth-utils": "^0.5.15"

  "@iconify-json/heroicons": "^1.2.2"
  "@iconify-json/simple-icons": "^1.2.22"
  "@iconify-json/lucide": "^1.2.25"
  "@nuxt/eslint": "^0.7.5"
  "better-sqlite3": "^11.8.1"
  "drizzle-kit": "^0.30.2"
  "vue-tsc": "~2.1.10"
  "wrangler": "^3.105.1"
